### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by liuxin-SH** [weihaoysgs/ssvio#1]
您好，我运行出现了段错误，请问您有这个问题吗？
![image](https://github.com/weihaoysgs/ssvio/assets/56961236/03c4efc6-9ef5-40d0-8c3a-b50fc9514ff1)

**Comment by weihaoysgs** [comment]
检查一下路径啥的对不对呢，我看可能是一些路径没配对？
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月18日 13:10 |
| 收件人 | ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [weihaoysgs/ssvio] 段错误 (Issue #1) |

您好，我运行出现了段错误，请问您有这个问题吗？

**Comment by liuxin-SH** [comment]
经过调试发现运行到这段代码后出现段错误
 viewpoint_X_ = ssvio::Setting::Get<float>("Viewer.ViewpointX");
 请问您出现过这个问题吗？
 
![image](https://github.com/weihaoysgs/ssvio/assets/56961236/adb45c0a-bd45-4418-a9d2-181d0508d05e)

**Comment by liuxin-SH** [comment]
应该是配置文件没有加载进去，改成这样就可以了
![image](https://github.com/weihaoysgs/ssvio/assets/56961236/a602bf04-7508-4549-aaf7-2a24e06d4ed3)

**Comment by liuxin-SH** [comment]
找到问题了，我使用的是OPENCV4，这样改就可以了
![image](https://github.com/weihaoysgs/ssvio/assets/56961236/0273d503-0515-40e4-bb9f-89a8f1119663)

**Comment by weihaoysgs** [comment]
ok
